import { FormArray, FormControl, Validators } from '@angular/forms';
import { QuotationForm } from '../core/types';
import { TypedFormControls } from '@shared/types/types-form';

export function buildQuotationForm(): TypedFormControls<QuotationForm> {
  return {
    serie_id: new FormControl<number | null>(null),
    numero: new FormControl<string | null>(null),
    numero_completo: new FormControl<string | null>({ value: null, disabled: true }),
    fecha_emision: new FormControl<string | null>({ value: new Date().toISOString().split('T')[0], disabled: true }, [Validators.required]),
    fecha_valido_hasta: new FormControl<string | null>(null),
    mostrar_fecha_valido_hasta: new FormControl<boolean>(false),
    emp_id: new FormControl<number | null>(null),
    suc_id: new FormControl<number | null>(null),
    cli_id: new FormControl<number | null>(null),
    nombre_contacto: new FormControl<string | null>(null),
    telefono_contacto: new FormControl<string | null>(null),
    correo_contacto: new FormControl<string | null>(null),
    area_contacto: new FormControl<string | null>(null),
    mon_id: new FormControl<number | null>(null),
    mostrar_moneda: new FormControl<boolean>(false),
    cot_subtotal: new FormControl<number | null>(null),
    cot_igv: new FormControl<number | null>(null),
    igv_requerido: new FormControl<boolean>(false),
    cot_total: new FormControl<number | null>(null),
    mostrar_total: new FormControl<boolean>(false),
    cot_descuento: new FormControl<number | null>(null),
    observaciones: new FormControl<string | null>(null),
    mostrar_observaciones: new FormControl<boolean>(false),
    condiciones_pago: new FormControl<string | null>(null),
    mostrar_condiciones_pago: new FormControl<boolean>(false),
    tipo_pago_id: new FormControl<number | null>(null),
    mostrar_tipo_pago: new FormControl<boolean>(false),
    forma_pago: new FormControl<string | null>(null),
    mostrar_forma_pago: new FormControl<boolean>(false),
    plazo_entrega: new FormControl<string | null>(null),
    mostrar_plazo_entrega: new FormControl<boolean>(false),
    lugar_entrega: new FormControl<string | null>(null),
    mostrar_lugar_entrega: new FormControl<boolean>(false),
    garantia: new FormControl<string | null>(null),
    mostrar_garantia: new FormControl<boolean>(false),
    consideraciones: new FormControl<string | null>(null),
    mostrar_consideraciones: new FormControl<boolean>(false),
    servicio_complementario: new FormControl<string | null>(null),
    mostrar_servicio_complementario: new FormControl<boolean>(false),
    cli_documento: new FormControl<string | null>(null),
    cli_direcc: new FormControl<string | null>(null),
    tip_id: new FormControl<number | null>(null),
    usu_id: new FormControl<number | null>(null),
    // Temporary field for product selection (not sent to backend in final request)
    prod_id: new FormControl<number | null>(null),
    detalles: new FormArray<any>([]),
  };
}
